export const APP_SET_APP_INITIALIZE = 'APP/SET_APP_INITIALIZE';
export const APP_SET_MAIN_IMAGE = 'APP/SET_MAIN_IMAGE';
export const APP_SET_API = 'APP/SET_API';
export const APP_SET_APP_STATUS = 'APP/SET_APP_STATUS';
